### PR TITLE
373 deploying the sample data fails

### LINKED ISSUE #373: Deploying the sample data fails
```
[root@host Doctrine] php deploy/DeploySampleDataRunner.php sampleData
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqli.so' - /usr/lib64/php/modules/mysqli.so: symbol client_errors, version libmysqlclient_18 not defined in file libmysqlclient.so.18 with link time reference in Unknown on line 0
Deploying Sample Data from sampleData
Added Projects OK
Added Scopes OK
Added NGIs OK
Added Sites and JOINED to NGIs OK
Added Services, EndpointLocations and JOINED associations OK
Added Users OK
Added Site level Roles OK
Added NGI level Roles OK
Added EGI level Roles OK
PHP Fatal error:  Uncaught exception 'LogicException' with message 'Unknown ServiceGroup key in input XML: GOCDB_PORTAL_URL' in /usr/share/GOCDB5/lib/Doctrine/deploy/AddServiceGroups.php:39
Stack trace:
#0 /usr/share/GOCDB5/lib/Doctrine/deploy/DeploySampleDataRunner.php(54): require()
#1 {main}
  thrown in /usr/share/GOCDB5/lib/Doctrine/deploy/AddServiceGroups.php on line 39
```

### PR DESCRIPTION
**Pull request by rowan04**
Resolves #373

### CODE REVIEW

File: lib/Doctrine/deploy/AddServiceGroups.php [hunk 1]
```diff
@@ -36,9 +45,10 @@
                 $scope = (string) $value;
                 break;
             default:
```
Comment (tofu-rocketry) [inline lib/Doctrine/deploy/AddServiceGroups.php:47]: Do we need a `default` if it's just doing a `break`? (N.B. I'm not good at PHP, so that's a genuine question!)

File: lib/Doctrine/deploy/AddServiceGroups.php [hunk 2]
```diff
@@ -10,6 +10,15 @@
 $stFileName = __DIR__ . "/" . $GLOBALS['dataDir'] . "/ServiceGroups.xml";
 $sts = simplexml_load_file($stFileName);
 
+// Checking the XML file has parsed correctly
+if ($sts === false) {
+    echo "There were errors parsing the XML file.\n";
+    foreach (libxml_get_errors() as $error) {
+        echo $error->message;
```
Comment (tofu-rocketry) [inline lib/Doctrine/deploy/AddServiceGroups.php:17]: Maybe add a comment nothing that `$error` will be a libXMLError object?

**Review by tofu-rocketry — COMMENTED** [review]
I'd suggest merging the code quality fixes with the first commit, and then splitting that out into a commit around line 39 with a good commit messages explaining _why_ that change, and then a 2nd commit with the new check.

File: lib/Doctrine/deploy/AddServiceGroups.php (hunk 1 above)
Comment (gregcorbett) [reply lib/Doctrine/deploy/AddServiceGroups.php:47]: what key was hitting the `default` case and causing the LogicException to be thrown? Just wondering if that should in fact be handled.

Comment (rowan04) [reply lib/Doctrine/deploy/AddServiceGroups.php:47]: i believe GOCDB_PORTAL_URL if i remember rightly

Comment (gregcorbett) [reply lib/Doctrine/deploy/AddServiceGroups.php:47]: So from speaking to @ineilson who added `lib/Doctrine/deploy/AddServiceGroups.php`, it was originally added to handle a stripped down subset of the GOCDB PI XML for the get_service_group method that's contained within the simpleSampleData. 

Now that the sample data is being refreshed (#394), the simple sample data can be deleted and this XML handling should be extended to handle the full XML output.

But those can be handled in future issues.

File: lib/Doctrine/deploy/AddServiceGroups.php (hunk 2 above)
Comment (gregcorbett) [reply lib/Doctrine/deploy/AddServiceGroups.php:17]: @rowan04 could you add this comment?

**Comment by tofu-rocketry** [comment]
We've merged the original commits, and split them into two new ones based on the functionality changed.

( @rowan04 May bad, but I forgot to get you to add a note like this to the PR, which confused @gregcorbett - it's useful when you re-write the history.)

File: lib/Doctrine/deploy/AddServiceGroups.php (hunk 2 above)
Comment (rowan04) [reply lib/Doctrine/deploy/AddServiceGroups.php:17]: ok

**Comment by rowan04** [comment]
> We've merged the original commits, and split them into two new ones based on the functionality changed.
> 
> ( @rowan04 May bad, but I forgot to get you to add a note like this to the PR, which confused @gregcorbett - it's useful when you re-write the history.)

ok!

File: lib/Doctrine/deploy/AddServiceGroups.php (hunk 1 above)
Comment (rowan04) [reply lib/Doctrine/deploy/AddServiceGroups.php:47]: ok, so what should i do next with this pull request?

Comment (rowan04) [reply lib/Doctrine/deploy/AddServiceGroups.php:47]: ok!

Comment (gregcorbett) [reply lib/Doctrine/deploy/AddServiceGroups.php:47]: > once [this](https://github.com/GOCDB/gocdb/pull/393/files#diff-267c881b565179a711a7be52ccfb482aae95438e1cf8eb805b6a0a803306f8ed) comment has been added, I will merge the PR and open the follow up issues 😄

just leaving this conversation unresolved to remind me of this 😋

File: lib/Doctrine/deploy/AddServiceGroups.php (hunk 2 above)
Comment (rowan04) [reply lib/Doctrine/deploy/AddServiceGroups.php:18]: done

File: lib/Doctrine/deploy/AddServiceGroups.php (hunk 1 above)
Comment (gregcorbett) [reply lib/Doctrine/deploy/AddServiceGroups.php:48]: > lib/Doctrine/deploy/AddServiceGroups.php

See #415 and #416

**Review by gregcorbett — APPROVED** [review]
LGTM

**Comment by gregcorbett** [comment]
Rebasing
