### PR TITLE
Fix email issues

### LINKED ISSUE #64: Enrich and personalise emails
We all just received the following really generic emails, it would be nice if they contained a bit more information, for example, my name, the user-name that requires attention, what "attention" they require.
This might also help it look less like a phishing attempt.

> Dear GOCDB User,
> 
> A user has requested a role that requires attention.
> 
> You can approve or deny this request here:
> 
> https://goc.egi.eu/portal/index.php?Page_Type=Role_Requests
> 
> Note: This role may already have been approved or denied by another GocDB User

### LINKED ISSUE #163: NotificationService will try and send emails even if send_email is set to false.
That's because whether to try and send emails or not is [hard coded](https://github.com/GOCDB/gocdb/blob/dev/lib/Gocdb_Services/NotificationService.php#L116) to `true` in NotificationService.php. This should be read from the local config file.

### LINKED ISSUE #168: emails "from GOCDB" should come from gocdb-admins@mailman.egi.eu
This is because, on SL7 at least, emails (such as role request emails) appear to come from `*@goc.stfc.ac.uk` (because `goc.egi.eu` "points" at `goc.stfc.ac.uk` and some magic resolves the domain in the email address).

This might be confusing to user, I feel gocdb-admins@mailman.egi.eu would be less confusing - especially as that would be any reply-to address.

### PR DESCRIPTION
**Pull request by jrha**
Depends on #238 

Fixes #64, fixes #163 and fixes #168.

### CODE REVIEW

**Comment by gregcorbett** [comment]
I've had my hands all over this now, so I'd appreciate a review from @tofu-rocketry or @ineilson.

For my own future reference:
- This doesn't seem to email a GOCDB admin if they are the only person who can approve a role (I'll open an issue about this)
- Not sure how it behaves with ServiceGroups (I'll investigate, but that should hold up merging the PR)

**Comment by gregcorbett** [comment]
Looking at Travis - I should merge #238 first.

File: lib/Gocdb_Services/NotificationService.php [hunk 1]
```diff
@@ -97,33 +93,14 @@ public function roleRequest($entity) {
...
-            // Get the PortalURL to create an accurate link to the role approval view
-            $localInfoLocation = __DIR__ . "/../../config/local_info.xml";
-            $localInfoXML = simplexml_load_file ( $localInfoLocation );
-            $webPortalURL = $localInfoXML->local_info->web_portal_url;
-
-            // Email content
-            $headers = "From: no-reply@goc.egi.eu";
-            $subject = "GocDB: A Role request requires attention";
+            // Remove duplicate user ids from array
+            $authorising_user_ids = array_unique ( $authorising_user_ids );
```
Comment (ineilson) [inline lib/Gocdb_Services/NotificationService.php:97]: The following 'if' implies a null is allowed which would generate a useless php Warning here.

**Review by ineilson — CHANGES_REQUESTED** [review]

File: lib/Gocdb_Services/NotificationService.php [hunk 2]
```diff
@@ -27,32 +28,32 @@ class NotificationService extends AbstractEntityService {
      *
      * @param Site/ServiceGroup/NGI/Project $entity
```
[the remark this answers is not in the document]
Comment (gregcorbett) [reply lib/Gocdb_Services/NotificationService.php:29]: What is the significance of reworking this?

File: lib/Gocdb_Services/NotificationService.php [hunk 3]
```diff
@@ -27,32 +28,32 @@ class NotificationService extends AbstractEntityService {
...
+        if ($entity->getRoles()->isEmpty()) {
+          // The entity has no roles.
+          $roles = [];
+        }
+        else {
+          // The entity has roles.
+          foreach ( $entity->getRoles () as $role ) {
+              $roles [] = $role;
+          }
         }
```
[the remark this answers is not in the document]
Comment (gregcorbett) [reply lib/Gocdb_Services/NotificationService.php:46]: This is less verbose 😄 , I'm not sure `$roles` is _needed_ either - but it is referenced later on.

File: lib/Gocdb_Services/NotificationService.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (ineilson) [reply lib/Gocdb_Services/NotificationService.php:29]: My understanding is that the original Type as 'Site/ServiceGroup/NGI/Project' is meaningless to phpDocumentor. What is expected is an instance of an OwnedEntity. Providing the correct type allows 'intelligent' code parsers to warn of type errors. Sadly, after 2 months, I've lost track of what example highlighted this.

[the remark this answers is not in the document]
Comment (gregcorbett) [reply lib/Gocdb_Services/NotificationService.php:29]: That makes sense 😄 

Is this better?

```suggestion
     * @param OwnedEntity $entity
```

Seems weird to still have `Site/ServiceGroup/NGI/Project` at the end of `@param OwnedEntity $entity Site/ServiceGroup/NGI/Project`

[the remark this answers is not in the document]
Comment (ineilson) [reply lib/Gocdb_Services/NotificationService.php:29]: Perhaps, more completely -
```suggestion
     * @param OwnedEntity $entity An instance of Site,Service,NGI,Project or other OwnedEntity.
     * @return void

File: lib/Gocdb_Services/NotificationService.php [hunk 4]
```diff
@@ -65,23 +66,18 @@ public function roleRequest($entity) {
...
 
         /*
          * No users are able to grant the role or there are no users over this entity. In this case we will email the parent entity for approval
          */
-        if ($emails == null || count($emails) == 0) {
+        if ($authorising_user_ids == null || count($authorising_user_ids) == 0) {
             if ($entity instanceof \Site) {
-                $this->roleRequest ( $entity->getNgi () ); // Recursivly call this function to send email to the NGI users
+                $this->roleRequest ( $role_requested, $requesting_user, $entity->getNgi () ); // Recursivly call this function to send email to the NGI usero
```
Comment (ineilson) [inline lib/Gocdb_Services/NotificationService.php]:
```suggestion
                $this->roleRequest ( $role_requested, $requesting_user, $entity->getNgi () ); // Recursivly call this function to send email to the NGI users
```

File: lib/Gocdb_Services/NotificationService.php [hunk 5]
```diff
@@ -136,12 +92,47 @@ public function roleRequest($entity) {
...
+    /**
+    * Return the PortalURL to enable an accurate link to the role approval view to be created
+    */
+    private function getWebPortalURL() {
+        return \Factory::getConfigService()->GetPortalURL();
+    }
+
+    private function sendEmail($roleRequested, $requestingUser, $entityName, $approvingUser) {
+        $subject = sprintf(
+            'GocDB: A Role request from %1$s over %2$s requires your attention',
```
Comment (ineilson) [inline lib/Gocdb_Services/NotificationService.php:111]: Not introduced by these changes, but I don't know why we would use a mixed case variation. 
```suggestion
            'GOCDB: A Role request from %1$s over %2$s requires your attention',
```

**Review by ineilson — APPROVED** [review]

File: lib/Gocdb_Services/NotificationService.php (hunk 4 above)
Comment (gregcorbett) [reply lib/Gocdb_Services/NotificationService.php]: Fixed in 263353a

**Comment by gregcorbett** [comment]
I've squashed some of my more "bug-fixy" commits into other commits but decided to leave the majority to not conflate moving code about and changing behaviour.

> As a note to Future Greg, one of these commits reverts another one of these commits - that at least can be squashed.

Just this and a final test (can it still send emails after the rebase) between us and GOCDB 5.8!

**Comment by gregcorbett** [comment]
> As a further note to Future Greg, print_r is also discouraged by codacy - but in a less severe way... so progress?

I'm going to ignore this, as I can't find an alternative and the PSR-12: Extended Coding Style examples make use of `echo` (vaguely relevant #270)

**Comment by gregcorbett** [comment]
@ineilson could I get your seal of approval? 🦭

File: lib/Gocdb_Services/NotificationService.php [hunk 6]
```diff
@@ -97,33 +73,14 @@ public function roleRequest($entity) {
...
-                       echo "Email: " . $email . "<br>";
-                       echo "Subject: " . $subject . "<br>";
-                       echo "Body: " . $body . "<br>";
-                    }
+            if (!empty($authorisingUserIds)) {
+                foreach ( $authorisingUserIds as $userId ) {
+                    $approvingUser = \Factory::getUserService()->getUser($userId);
+                    $this->sendEmail($roleRequested, $requestingUser, $entity->getName(), $approvingUser);
                 }
             }
```
Comment (ineilson) [inline lib/Gocdb_Services/NotificationService.php:85]: Haven't we already checked `if (count($authorisingUserIds) == 0) {` above and array_unique won't empty it?
```suggestion
           foreach ( $authorisingUserIds as $userId ) {
                $approvingUser = \Factory::getUserService()->getUser($userId);
                $this->sendEmail($roleRequested, $requestingUser, $entity->getName(), $approvingUser);
            }
```

File: lib/Gocdb_Services/NotificationService.php [hunk 7]
```diff
@@ -25,65 +26,40 @@ class NotificationService extends AbstractEntityService {
...
 
-            // remove admin from enabling roles
-            /*$position = array_search ( 'GOCDB_ADMIN', $enablingRoles );
-            if ($position != null) {
-                unset ( $enablingRoles [$position] );
-            }*/
-            // Get the users email and add it to the array if they have an enabling role
-            if (count ( $enablingRoles ) > 0) {
-                $emails [] = $role->getUser ()->getEmail ();
+            // If they can, add thier user id to the list of authorising user
```
Comment (ineilson) [inline lib/Gocdb_Services/NotificationService.php:47]:
```suggestion
            // If they can, add their user id to the list of authorising user
```

File: lib/Gocdb_Services/NotificationService.php [hunk 8]
```diff
@@ -25,65 +26,40 @@ class NotificationService extends AbstractEntityService {
...
+            if (count($enablingRoles) > 0) {
+                $authorisingUserIds [] = $user->getId();
             }
         }
 
-        /*
-         * No users are able to grant the role or there are no users over this entity. In this case we will email the parent entity for approval
-         */
-        if ($emails == null || count($emails) == 0) {
+        // If there are no users are able to grant the role over this entity,
```
Comment (ineilson) [inline lib/Gocdb_Services/NotificationService.php:54]:
```suggestion
        // If there are no users that are able to grant the role over this entity,
```

**Review by ineilson — APPROVED** [review]

File: lib/Gocdb_Services/NotificationService.php (hunk 6 above)
Comment (gregcorbett) [reply lib/Gocdb_Services/NotificationService.php:85]: Good point!

**Comment by gregcorbett** [comment]
Suggestions applied, @ineilson could I get a fresh seal of approval?

**Review by ineilson — APPROVED** [review]
