### PR TITLE
GT-95 Include failing test and error string in monitoring message

### LINKED ISSUE #223: ops_monitor_check.php message on error ignores which test is failing
`htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php` will show the error message

> GOCDB Web Portal is unable to connect to the GOCDB back end database\n

regardless of which test is failing (it could be a API problem, a portal problem or a problem around the local_info.xml). It could give a more generic error message like the `htdocs/web_portal/GOCDB_monitor/check.php` page does. One may then ask "why do we have two very similiar pages?"

### PR DESCRIPTION
**Pull request by ineilson**
Fixes #223.

### CODE REVIEW

**Review by gregcorbett — CHANGES_REQUESTED** [review]
LGTM, please rebase this to fix the conflicts 😄

File: htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php [hunk 1]
```diff
@@ -1,49 +1,22 @@
...
-    die();
+if (isset($_REQUEST['fake_failure'])) {
+    $message = 'Fake failure';
+    $errorCount = 1;
+} else {
+    $errorCount = run_tests($message);
 }
 
-if ($counts["error"] != 0) {
+if ($errorCount != 0) {
```
Comment (gregcorbett) [inline htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php:20]: How does `$errorCount` get populated? In `check.php`, there is this line

```
$errorCount = run_tests($message);
```

 `ops_monitor_check.php` doesn't seem to call that method.

Comment (gregcorbett) [reply htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php:20]: ah you're right, didn't see that bit. Which perhaps suggests some additional comment is needed.

Maybe something like

```
/* If someone wants to test the failure, they can fake one using
 * the fake_failure parameter. 
 * Otherwise, run the tests. */
```

Comment (ineilson) [reply htdocs/web_portal/GOCDB_monitor/ops_monitor_check.php:20]: There is already 'something like' that in the header which seems to me a better place.

**Review by gregcorbett — APPROVED** [review]
LGTM

**Comment by gregcorbett** [comment]
rebasing on top of latest dev
